<?php
$payerAuthInformation = $block->getPayerAuthenticationAdditionalInformation();
$additionalInformation = $block->getAdditionalInformation();
?>
<?php if (!empty($payerAuthInformation)): ?>
    <div class="admin__page-section-item-title" style="margin-top: 1.5rem">
        <span class="title"><?= $escaper->escapeHtml(__("Payer Authentication")) ?></span>
    </div>
    <table class="data-table admin__table-secondary">
        <?php foreach ($payerAuthInformation as $label => $value): ?>
            <tr>
                <th><?= $escaper->escapeHtml($label) ?>:</th>
                <td>
                    <?= /* @noEscape */ nl2br($escaper->escapeHtml(implode("\n", $block->getValueAsArray($value, true)))) ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php endif; ?>
<?php if (!empty($additionalInformation)): ?>
    <div class="admin__page-section-item-title" style="margin-top: 1.5rem">
        <span class="title"><?= $escaper->escapeHtml(__("Additional Information")) ?></span>
    </div>
<?php endif; ?>
<table class="data-table admin__table-secondary">
    <?php foreach ($additionalInformation as $label => $value): ?>
        <tr>
            <th><?= $escaper->escapeHtml($label) ?>:</th>
            <td>
                <?= /* @noEscape */ nl2br($escaper->escapeHtml(implode("\n", $block->getValueAsArray($value, true)))) ?>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
