<?php
/**
 * Copyright © 2020 CyberSource. All rights reserved.
 * See accompanying LICENSE.txt for applicable terms of use and license.
 */

/** @var $block \CyberSource\WeChatPay\Block\Order\Info\Qr */
?>
<?php if ($block->isApplicable()): ?>
    <a href="javascript:void(0);" class="action qr" data-trigger="wechatpayqr">
        <span><?= /* @noEscape */ $block->getLabel() ?></span>
    </a>
<?php endif; ?>

 
