<iframe id="step-up-iframe" name="step-up-iframe" height="" width="" style="display: none; position :fixed; top: 50%; left: 50%; transform: translate(-50%, -50%); z-index: 9999; background-color: white; border: 1px solid black; padding: 10px;"></iframe>
<div style="display:none;height: 100vh; width: 100vw; background: rgba(0, 0, 0, 0.8); z-index: 999; position :fixed; " id="overlay" ></div>
<form id="step-up-form" target="step-up-iframe" method="post" action="">
    <input id="step-up-form-input"type="hidden" name="JWT" value=""/>
</form>