<?php
// @codingStandardsIgnoreFile

/** @var \Magento\Payment\Block\Transparent\Iframe $block */
$params = $block->getParams();
?>
var require = window.top.require;
require(
    [
        'jquery',
        'Magento_Checkout/js/model/quote',
        'Magento_Checkout/js/action/place-order',
        'Magento_Checkout/js/action/redirect-on-success',
        'Magento_Checkout/js/model/full-screen-loader',
        'CyberSource_ThreeDSecure/js/view/payment/cardinal'
    ],
    function ($, quote, placeOrderAction, redirectOnSuccessAction, fullScreenLoader, Cardinal) {
        var parent = window.top;

        <?php if (isset($params['email'])): ?>
        quote.guestEmail = '<?= /* noescape */ $params['email'] ?>';
        <?php endif; ?>

        <?php if ($params['3ds_active'] ?? false): ?>
        Cardinal.init(false);
        <?php endif; ?>

        $(parent).trigger('clearTimeout');
        fullScreenLoader.startLoader();

        $.when(
            <?php if ($params['3ds_active'] ?? false): ?>
                    Cardinal.setup()
                ).then(
            <?php endif; ?>
            function () {
                var deferred = $.Deferred();
                placeOrderAction(<?= /* noescape */ json_encode($params['payload'] ?? []) ?>).then(
                    function (result) {
                        deferred.resolve(result);
                    },
                    function (result) {
                        deferred.reject(result);
                    }
                );
                return deferred.promise();
            }
        ).done(
            function () {
                redirectOnSuccessAction.execute();
            }
        ).fail(
            function () {
                var parent = window.top;
                $(parent).trigger('clearTimeout');
                fullScreenLoader.stopLoader();
            }
        );
    }
);
