<?php

/** @var \Magento\Payment\Block\Transparent\Iframe $block */
$params = $block->getParams();
?>
<script>
    <?php if (isset($params['redirect'])) : ?>
    window.location = "<?= $block->escapeUrl($params['redirect']) ?>";
    <?php elseif (isset($params['redirect_parent'])) : ?>
    var require = window.top.require;
    require(
        [
            'jquery'
        ],
        function ($) {
            var parent = window.top;
            $(parent).trigger('clearTimeout');
            parent.location = "<?= $block->escapeUrl($params['redirect_parent']) ?>";
        }
    );
    <?php elseif (isset($params['error_msg'])) : ?>
    var require = window.top.require;
    require(
        [
            'jquery',
            'Magento_Ui/js/model/messageList',
            'mage/translate',
            'Magento_Checkout/js/model/full-screen-loader'
        ],
        function ($, globalMessageList, $t, fullScreenLoader) {
            var parent = window.top;
            $(parent).trigger('clearTimeout');
            fullScreenLoader.stopLoader();
            globalMessageList.addErrorMessage({
                message: $t('An error occurred on the server. Please try to place the order again.')
            });
        }
    );
    <?php elseif (isset($params['multishipping'])) : ?>
    var require = window.top.require;
    require(
        [
            'jquery'
        ],
        function ($) {
            var parent = window.top;
            $(parent).trigger('clearTimeout');
            $(parent.document).find('#multishipping-billing-form').submit();
        }
    );
    <?php elseif (isset($params['order_success'])) : ?>
    window.top.location = "<?= $block->escapeUrl($params['order_success']) ?>";
    <?php else : ?>
        <?php echo $block->getChildHtml('3ds_continue'); ?>
    <?php endif; ?>
</script>
