<?php
use CyberSource\PayPal\Block\Customer\VaultTokenRenderer;
use Magento\Vault\Api\Data\PaymentTokenInterface;

/** @var VaultTokenRenderer $block */
$confirmDeleteMessage = sprintf(
    '%s %s (%s)?',
    __('Are you sure you want to delete this Billing Agreement'),
    ' started at ' . $block->getDate(),
    $block->getEmail()
);
?>
<tr>
    <td data-th="<?= $escaper->escapeHtml(__('Payment Gateway')) ?>" class="col">
        <span><?= $escaper->escapeHtml(__('PayPal Billing Agreement')) ?></span>
    </td>
    <td data-th="<?= $escaper->escapeHtml(__('ID')) ?>" class="col">
        <span><?= $escaper->escapeHtml($block->getMaskedId()) ?></span>
    </td>
    <td data-th="<?= $escaper->escapeHtml(__('Payer Account')) ?>" class="col">
        <span><?= $escaper->escapeHtml($block->getEmail()) ?></span>
    </td>
    <td data-th="<?= $escaper->escapeHtml(__('Signed')) ?>" class="col">
        <span><?= $escaper->escapeHtml($block->getDate()) ?></span>
    </td>
    <td data-th="<?= $escaper->escapeHtml(__('Actions')) ?>" class="col actions">
        <form class="form" action="<?= $escaper->escapeUrl($block->getUrl('vault/cards/deleteaction')) ?>" method="post">
            <input name="<?= $escaper->escapeHtml(PaymentTokenInterface::PUBLIC_HASH) ?>"
                   value="<?= $escaper->escapeHtml($block->getToken()->getPublicHash()) ?>"
                   type="hidden"/>
            <button type="submit" class="action delete"
                    data-mage-init='{
                        "Magento_Vault/js/customer_account/deleteWidget":{
                            "type": "popup",
                            "modalClass": "my-vault-tokens-popup",
                            "toggleEvent": "click",
                            "title": "<?= $escaper->escapeHtml(__('Delete')) ?>",
                            "content":"<?= $escaper->escapeHtml($confirmDeleteMessage) ?>"
                        }
                    }'>
                <span><?= $escaper->escapeHtml(__('Delete')) ?></span>
            </button>
        </form>
    </td>
</tr>
