<?php

/* @var $block \CyberSource\ThreeDSecure\Block\cardinal */

?>
<script type="text/javascript">

    require.config({
        paths: {
            cardinal: '<?php echo $block->isSandbox()
                ?
                'https://centinelapistag.cardinalcommerce.com'
                :
                'https://centinelapi.cardinalcommerce.com'; ?>'
        },
        shim: {
            cardinal: {
                exports: 'Cardinal'
            }
        }

    });

</script>

