<?php
 
// @codingStandardsIgnoreFile
/**
* Note: This mark is a requirement of PayPal
* @var \CyberSource\PayPal\Block\Express\Form $block
* @see \CyberSource\PayPal\Block\Express\Form
*/
$url = $block->escapeUrl($block->getPaymentAcceptanceMarkHref());
?>
<!-- PayPal Logo -->
<img src="<?php echo $block->escapeUrl($block->getPaymentAcceptanceMarkSrc()) ?>"
     alt="<?php echo $block->escapeHtml(__('Acceptance Mark')) ?>" class="paypal icon"/>
<a href="<?php echo $block->escapeUrl($url) ?>"
   onclick="javascript:window.open(
'<?= $block->escapeUrl($url) ?>'
           'olcwhatispaypal',
           'toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=yes, ,' +
           'left=0, top=0, width=400, height=350'
       ); return false;"
   class="action paypal about">
    <?php if ($block->getPaymentWhatIs()) {
        echo $block->escapeHtml(__($block->getPaymentWhatIs()));
} else {
        echo $block->escapeHtml(__('What is PayPal?'));
} ?>
</a>
<!-- PayPal Logo -->