<?php
/* @var $block \CyberSource\SecureAcceptance\Block\Flex */
$clientLibraryUrl = $block->isSandbox() ? $block->getClientLibrary() : $block->getProductionClientLibrary();
$integrityValue = $block->getClientLibraryIntegrity();
$crossOriginValue = 'anonymous';

// Ensure values default to empty strings if not set
$clientLibraryUrl = $clientLibraryUrl ?? '';
$integrityValue     = $integrityValue ?? '';
?>

<script type="text/javascript">
    // Convert PHP values to JavaScript variables
    var clientLibraryUrl = '<?php  /* @noEscape */ echo  $clientLibraryUrl; ?>';
    var integrityValue = '<?php  /* @noEscape */  echo $integrityValue; ?>';
    var crossOriginValue = '<?php  /* @noEscape */ echo $crossOriginValue; ?>';

    // Configure require.js and ensure we don't pass in null values
    require.config({
        paths: {
            "flex-microform": '<?php  /* @noEscape */ echo str_replace(".js", "", $clientLibraryUrl); ?>'
        },
        shim: {
            "flex-microform": {
                exports: 'Flex'
            }
        }
    });

    // Dynamically append the script tag with integrity and cross-origin attributes if available
    if (clientLibraryUrl !== '' && integrityValue !== '') {
        var script = document.createElement('script');
        script.src = clientLibraryUrl;
        script.integrity = integrityValue;
        script.crossOrigin = crossOriginValue;
        document.head.appendChild(script);
    } else {
        console.warn('Unable to load the CyberSource flex microform. Please check your configuration.');
    }
</script>
