<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See LICENSE.txt for license details.
 */

use CyberSource\PayPal\Block\Express\InContext\Minicart\Button;

/** @var \CyberSource\PayPal\Block\Express\InContext\Component $block */

$configuration = [
    '*' => [
        'CyberSource_PayPal/js/in-context/express-checkout' => [
            'id' => Button::PAYPAL_BUTTON_ID,
            'path' => $block->getUrl(
                'cybersourcepaypal/express/gettoken',
                [
                    '_secure' => $block->getRequest()->isSecure()
                ]
            ),
            'merchantId' => $block->getMerchantId(),
            'button' => $block->isButtonContext(),
            'clientConfig' => [
                'locale' => $block->getLocale(),
                'environment' => $block->getEnvironment(),
                'button' => [
                    Button::PAYPAL_BUTTON_ID,
                ],
            ]
        ]
    ]
];
?>
<div style="display: none;" id="<?= $escaper->escapeHtmlAttr($block->getMerchantId()) ?>"></div>

<script type="text/x-magento-init">
<?= $escaper->escapeHtml(json_encode($configuration)) ?>
</script>
