<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See LICENSE.txt for license details.
 */

use CyberSource\PayPal\Block\Express\InContext\Minicart\Button;

/**
 * @var \CyberSource\PayPal\Block\Express\InContext\Minicart\Button $block
 */
$config = [
    'CyberSource_PayPal/js/in-context/button' => [
        'id' => $escaper->escapeHtml($block->getContainerId()),
        'linkDataAction' => $escaper->escapeHtml($block->getLinkAction()),
        'paypalButton' => $escaper->escapeHtml(Button::PAYPAL_BUTTON_ID),
        'addToCartSelector' => $escaper->escapeHtml($block->getAddToCartSelector())
    ]
];
?>

<div data-mage-init='<?= $escaper->escapeHtml(json_encode($config)) ?>'
     class="paypal checkout paypal-logo <?= $escaper->escapeHtml($block->getContainerId()) ?>-container">
    <a data-action="<?= $escaper->escapeHtml($block->getLinkAction()) ?>" href="#">
        <img class="paypal-button-hidden"
             src="<?= $escaper->escapeHtml($block->getImageUrl()) ?>"
             alt="Check out with PayPal" />
    </a>
</div>
