<?php

$code = $block->escapeHtml($block->getMethodCode());
$ccType = $block->getInfoData('cc_type');
$ccExpYear = $block->getInfoData('cc_exp_year');
$ccExpMonth = $block->getInfoData('cc_exp_month');

?>

<fieldset id="payment_form_<?= $block->escapeHtml($block->getMethodCode()) ?>"
          style="display:none"
          class="admin__fieldset payment-method"
          data-mage-init='{"CyberSource_SecureAcceptance/js/microform": {
                "controller":"<?= $block->escapeHtml($block->getRequest()->getControllerName()) ?>",
                "gateway":"<?= /* @noEscape */ $code ?>",
                "orderSaveUrl":"<?= $block->escapeUrl($block->getOrderUrl()) ?>",
                "cgiUrl":"<?= $block->escapeUrl($block->getCgiUrl()) ?>"}, "validation":[]}'>

    <div class="admin__field _required input-text-container">
        <label for="<?= /* @noEscape */ $code ?>_cc_type" class="admin__field-label">
            <span><?= $block->escapeHtml(__('Credit Card Type')) ?></span>
        </label>

        <div class="admin__field-control">
            <select id="<?= /* @noEscape */ $code ?>_cc_type"
                    data-container="<?= /* @noEscape */ $code ?>-cc-type"
                    name="payment[cc_type]"
                    data-validate='{required:true}'
                    class="admin__control-select">
                <option value=""><?= $block->escapeHtml(__('Please Select')) ?></option>
                <?php foreach ($block->getCcAvailableTypes() as $typeCode => $typeName): ?>
                    <option
                        value="<?= $block->escapeHtml($typeCode) ?>"<?php if ($typeCode == $ccType): ?> selected="selected"<?php endif ?>>
                        <?= $block->escapeHtml($typeName) ?>
                    </option>
                <?php endforeach ?>
            </select>
        </div>
    </div>

    <div class="admin__field _required field-number input-text-container">
        <label for="<?= /* @noEscape */ $code ?>_cc_number" class="admin__field-label">
            <span><?= $block->escapeHtml(__('Credit Card Number')) ?></span>
        </label>

        <div class="admin__field-control admin__control-text flex-input" id="<?= /* @noEscape */ $code ?>_cc_number">
            
        </div>
        <input type="hidden" name="microform"
            data-validate="{
                'microform-card-valid': {selector: '#<?= /* @noEscape */ $code ?>_cc_number', errorClass: 'mage-error'},
                'microform-card-valid-type': {selector: '#<?= /* @noEscape */ $code ?>_cc_number', errorClass: 'mage-error'}
            }"
        />
    </div>
    <div class="admin__field-control input-select-container">
        <select id="<?= /* @noEscape */ $code ?>_expiration" name="payment[cc_exp_month]"
                data-container="<?= /* @noEscape */ $code ?>-cc-month"
                class="admin__control-select admin__control-select-month"
                data-validate='{required:true, "validate-cc-exp":"#<?= /* @noEscape */ $code ?>_expiration_yr"}'>
            <?php foreach ($block->getCcMonths() as $k => $v): ?>
                <option
                    value="<?= /* @noEscape */ $k ? $block->escapeHtml($k) : '' ?>"
                    <?php if ($k == $ccExpMonth): ?> selected="selected"<?php endif; ?>>
                    <?= $block->escapeHtml($v) ?>
                </option>
            <?php endforeach ?>
        </select>

        <select id="<?= /* @noEscape */ $code ?>_expiration_yr" name="payment[cc_exp_year]"
                class="admin__control-select admin__control-select-year"
                data-container="<?= /* @noEscape */ $code ?>-cc-year" data-validate='{required:true}'>
            <?php foreach ($block->getCcYears() as $k => $v): ?>
                <option
                    value="<?= /* @noEscape */ $k ? $block->escapeHtml($k) : '' ?>"
                    <?php if ($k == $ccExpYear): ?> selected="selected"<?php endif ?>>
                    <?= $block->escapeHtml($v) ?>
                </option>
            <?php endforeach ?>
        </select>
    </div>
    
    <?php if ($block->hasVerification()): ?>
        <div class="admin__field _required field-cvv input-text-container" id="<?= /* @noEscape */ $code ?>_cc_type_cvv_div">
            <label for="<?= /* @noEscape */ $code ?>_cc_cid" class="admin__field-label">
                <span><?= $block->escapeHtml(__('Card Verification Number')) ?></span>
            </label>

            <div class="admin__field-control control admin__control-text cvv flex-input" id="<?= /* @noEscape */ $code ?>_cc_cid" >
                
            </div>

            <input  type="hidden"
                    name="microform-cvn"
                    data-validate="{'microform-card-valid-cvn': {selector: '#<?= /* @noEscape */ $code ?>_cc_cid', errorClass: 'mage-error'}}"
                    class="input-error"
            />
        </div>
    <?php endif; ?>
    
    <?= $block->getChildHtml() ?>
</fieldset>
<script>
    /**
     * Disable card server validation in admin
     */
    require(["Magento_Sales/order/create/form"], function () {
        order.addExcludedPaymentMethod('<?= /* @noEscape */ $code ?>');
    });
</script>
