<?php
$code = $escaper->escapeHtml($block->getMethodCode());
$method = $block->getMethod();
$controller = $escaper->escapeHtml($block->getRequest()->getControllerName());

/** @var CyberSource\Core\Helper\Data $helper */
$helper = $block->helper('CyberSource\Core\Helper\Data');
$orderUrl = $escaper->escapeUrl($helper->getPlaceOrderAdminUrl());
$tokens = $helper->getTokens($method->getStore());
?>

<fieldset class="admin__fieldset payment-method" id="payment_form_<?= /* @noEscape */ $code; ?>" style="display:none;">
    <div class="admin__field _required">
        <div class="admin__field-control">
            <?php if (!empty($tokens)): ?>
            <table class="admin__table-secondary">
                <?php foreach ($tokens as $token): ?>
                    <tr>
                        <th><?= $escaper->escapeHtml(__('Token')); ?></th>
                        <td><input type="radio" name="payment[token]" value="<?= $escaper->escapeHtml($token['token_id']); ?>">
                            <?= $escaper->escapeHtml($token['cc_number']); ?>
                        </td>
                    </tr>
                    <?php if ($helper->getGatewayConfig()->isCVVEnabled()): ?>
                        <tr>
                            <th><?= $escaper->escapeHtml(__('CVV')); ?></th>
                            <td><input type="number" name="payment[cvv]" maxlength="4"></td>
                        </tr>
                    <?php endif; ?>
                <?php endforeach; ?>
            </table>
            <?php else: ?>
                <?= $escaper->escapeHtml(__('No Tokens for this customer')); ?>
            <?php endif; ?>
        </div>
    </div>
</fieldset>
<script>
    require([
        'prototype',
        'Magento_Sales/order/create/scripts',
        "Magento_Sales/order/create/form",
        'CyberSource_Core/js/cybersource'
    ], function(){
        var cybersource = new Cybersource(
            '<?= $escaper->escapeJs($code); ?>',
            '<?= $escaper->escapeJs($controller); ?>',
            '<?= $escaper->escapeUrl($orderUrl); ?>',
            '<?= $escaper->escapeUrl($block->getUrl('*/*/save', ['_secure' => $block->getRequest()->isSecure()])); ?>'
        );
    });
</script>
