<?php

use Magento\Vault\Model\Ui\TokenUiComponentProviderInterface;

/** @var \Magento\Framework\View\Element\Template $block */

$details = $block->getData(TokenUiComponentProviderInterface::COMPONENT_DETAILS);
$hash = $block->getData(TokenUiComponentProviderInterface::COMPONENT_PUBLIC_HASH);
$icons = $block->getData('icons');
$icon = (isset($icons) && isset($details['type']) && isset($icons[$details['type']])) ? $icons[$details['type']] : null;
$code = $block->getData('code');
$id = $block->getData('id');

?>
<div data-mage-init='{
        "CyberSource_Core/js/vault": {
            "container": "payment_<?= /* @noEscape */ $id ?>",
            "publicHash": "<?= /* @noEscape */ $hash ?>",
            "code": "<?= /* @noEscape */ $code ?>"
        }
    }' id="payment_<?= /* @noEscape */ $id ?>" class="admin__field">
 
    <div class="admin__field-control control">
        <input class="required-entry" type="radio" id="token_switcher_<?= /* @noEscape */ $id ?>" name="payment[token_switcher]" disabled="disabled" />
        <label for="token_switcher_<?= /* @noEscape */ $id ?>">
            <?php if ($icon && isset($icon['url'])): ?>
            <img src="<?= /* @noEscape */ $icon['url'] ?>"
                 width="<?= /* @noEscape */ $icon['width'] ?>"
                 height="<?= /* @noEscape */ $icon['height'] ?>"
                 class="payment-icon">
                 <?php endif; ?>
            <span><?= /* @noEscape */ __('ending') ?> <?= $block->escapeHtml($details['maskedCC'])  ?></span>
            (<span><?= $block->escapeHtml($details['expirationDate']) ?></span>)
        </label>
    </div>
</div>